### ISSUE TITLE
As a developer I should have a mockup of all components and interactions before starting to develop

### ISSUE THREAD

**Issue by fredricklou523** [sumptingeneric/barback#29]

**Comment by deduced** [comment]
I decided to upload to Google Drive to keep things organized and shareable. We would only need to link to the specific UI / folder as needed in other stories rather than upload images again. 

Drive Folder: https://drive.google.com/drive/folders/1GOpMBRmaYejFS1bx2nBOWL8pt0dvzAxM?usp=sharing 

All files are broken up into: 
* user
* venue

and contain: 
* series of PNG files corresponding to each image
* a GIF that does the basic walk through
* an _overview.png that contains a bird's eye view of the UI with the associated links (to see the relationships between the UI screens)
